<?php

namespace App\Services\Riot\Match;

class ChallengesDto
{
    public function __construct(
        public ?int $associateWith12AssistStreakCount = null,
        public ?int $baronBuffGoldAdvantageOverThreshold = null,
        public ?float $controlWardTimeCoverageInRiverOrEnemyHalf = null,
        public ?int $earliestBaron = null,
        public ?int $earliestDragonTakedown = null,
        public ?int $earliestElderDragon = null,
        public ?int $earlyLaningPhaseGoldExpAdvantage = null,
        public ?int $fasterSupportQuestCompletion = null,
        public ?int $fastestLegendary = null,
        public ?int $hadAfkTeammate = null,
        public ?int $highestChampionDamage = null,
        public ?int $highestCrowdControlScore = null,
        public ?int $highestWardKills = null,
        public ?int $junglerKillsEarlyJungle = null,
        public ?int $killsOnLanersEarlyJungleAsJungler = null,
        public ?int $laningPhaseGoldExpAdvantage = null,
        public ?int $legendaryCount = null,
        public ?float $maxCsAdvantageOnLaneOpponent = null,
        public ?int $maxLevelLeadLaneOpponent = null,
        public ?int $mostWardsDestroyedOneSweeper = null,
        public ?int $mythicItemUsed = null,
        public ?int $playedChampSelectPosition = null,
        public ?int $soloTurretsLategame = null,
        public ?int $takedownsFirst25Minutes = null,
        public ?int $teleportTakedowns = null,
        public ?int $thirdInhibitorDestroyedTime = null,
        public ?int $threeWardsOneSweeperCount = null,
        public ?float $visionScoreAdvantageLaneOpponent = null,
        public ?int $InfernalScalePickup = null,
        public ?int $fistBumpParticipation = null,
        public ?int $voidMonsterKill = null,
        public ?int $abilityUses = null,
        public ?int $acesBefore15Minutes = null,
        public ?float $alliedJungleMonsterKills = null,
        public ?int $baronTakedowns = null,
        public ?int $blastConeOppositeOpponentCount = null,
        public ?int $bountyGold = null,
        public ?int $buffsStolen = null,
        public ?int $completeSupportQuestInTime = null,
        public ?int $controlWardsPlaced = null,
        public ?float $damagePerMinute = null,
        public ?float $damageTakenOnTeamPercentage = null,
        public ?int $dancedWithRiftHerald = null,
        public ?int $deathsByEnemyChamps = null,
        public ?int $dodgeSkillShotsSmallWindow = null,
        public ?int $doubleAces = null,
        public ?int $dragonTakedowns = null,
        public ?array $legendaryItemUsed = null,
        public ?float $effectiveHealAndShielding = null,
        public ?int $elderDragonKillsWithOpposingSoul = null,
        public ?int $elderDragonMultikills = null,
        public ?int $enemyChampionImmobilizations = null,
        public ?float $enemyJungleMonsterKills = null,
        public ?int $epicMonsterKillsNearEnemyJungler = null,
        public ?int $epicMonsterKillsWithin30SecondsOfSpawn = null,
        public ?int $epicMonsterSteals = null,
        public ?int $epicMonsterStolenWithoutSmite = null,
        public ?int $firstTurretKilled = null,
        public ?float $firstTurretKilledTime = null,
        public ?int $flawlessAces = null,
        public ?int $fullTeamTakedown = null,
        public ?float $gameLength = null,
        public ?int $getTakedownsInAllLanesEarlyJungleAsLaner = null,
        public ?float $goldPerMinute = null,
        public ?int $hadOpenNexus = null,
        public ?int $immobilizeAndKillWithAlly = null,
        public ?int $initialBuffCount = null,
        public ?int $initialCrabCount = null,
        public ?float $jungleCsBefore10Minutes = null,
        public ?int $junglerTakedownsNearDamagedEpicMonster = null,
        public ?float $kda = null,
        public ?int $killAfterHiddenWithAlly = null,
        public ?int $killedChampTookFullTeamDamageSurvived = null,
        public ?int $killingSprees = null,
        public ?float $killParticipation = null,
        public ?int $killsNearEnemyTurret = null,
        public ?int $killsOnOtherLanesEarlyJungleAsLaner = null,
        public ?int $killsOnRecentlyHealedByAramPack = null,
        public ?int $killsUnderOwnTurret = null,
        public ?int $killsWithHelpFromEpicMonster = null,
        public ?int $knockEnemyIntoTeamAndKill = null,
        public ?int $kTurretsDestroyedBeforePlatesFall = null,
        public ?int $landSkillShotsEarlyGame = null,
        public ?int $laneMinionsFirst10Minutes = null,
        public ?int $lostAnInhibitor = null,
        public ?int $maxKillDeficit = null,
        public ?int $mejaisFullStackInTime = null,
        public ?float $moreEnemyJungleThanOpponent = null,
        public ?int $multiKillOneSpell = null,
        public ?int $multikills = null,
        public ?int $multikillsAfterAggressiveFlash = null,
        public ?int $multiTurretRiftHeraldCount = null,
        public ?int $outerTurretExecutesBefore10Minutes = null,
        public ?int $outnumberedKills = null,
        public ?int $outnumberedNexusKill = null,
        public ?int $perfectDragonSoulsTaken = null,
        public ?int $perfectGame = null,
        public ?int $pickKillWithAlly = null,
        public ?int $poroExplosions = null,
        public ?int $quickCleanse = null,
        public ?int $quickFirstTurret = null,
        public ?int $quickSoloKills = null,
        public ?int $riftHeraldTakedowns = null,
        public ?int $saveAllyFromDeath = null,
        public ?int $scuttleCrabKills = null,
        public ?float $shortestTimeToAceFromFirstTakedown = null,
        public ?int $skillshotsDodged = null,
        public ?int $skillshotsHit = null,
        public ?int $snowballsHit = null,
        public ?int $soloBaronKills = null,
        public ?int $SWARM_DefeatAatrox = null,
        public ?int $SWARM_DefeatBriar = null,
        public ?int $SWARM_DefeatMiniBosses = null,
        public ?int $SWARM_EvolveWeapon = null,
        public ?int $SWARM_Have3Passives = null,
        public ?int $SWARM_KillEnemy = null,
        public ?float $SWARM_PickupGold = null,
        public ?int $SWARM_ReachLevel50 = null,
        public ?int $SWARM_Survive15Min = null,
        public ?int $SWARM_WinWith5EvolvedWeapons = null,
        public ?int $soloKills = null,
        public ?int $stealthWardsPlaced = null,
        public ?int $survivedSingleDigitHpCount = null,
        public ?int $survivedThreeImmobilizesInFight = null,
        public ?int $takedownOnFirstTurret = null,
        public ?int $takedowns = null,
        public ?int $takedownsAfterGainingLevelAdvantage = null,
        public ?int $takedownsBeforeJungleMinionSpawn = null,
        public ?int $takedownsFirstXMinutes = null,
        public ?int $takedownsInAlcove = null,
        public ?int $takedownsInEnemyFountain = null,
        public ?int $teamBaronKills = null,
        public ?float $teamDamagePercentage = null,
        public ?int $teamElderDragonKills = null,
        public ?int $teamRiftHeraldKills = null,
        public ?int $tookLargeDamageSurvived = null,
        public ?int $turretPlatesTaken = null,
        public ?int $turretsTakenWithRiftHerald = null,
        public ?int $turretTakedowns = null,
        public ?int $twentyMinionsIn3SecondsCount = null,
        public ?int $twoWardsOneSweeperCount = null,
        public ?int $unseenRecalls = null,
        public ?float $visionScorePerMinute = null,
        public ?int $wardsGuarded = null,
        public ?int $wardTakedowns = null,
        public ?int $wardTakedownsBefore20M = null
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            associateWith12AssistStreakCount: $data['12AssistStreakCount'] ?? null,
            baronBuffGoldAdvantageOverThreshold: $data['baronBuffGoldAdvantageOverThreshold'] ?? null,
            controlWardTimeCoverageInRiverOrEnemyHalf: $data['controlWardTimeCoverageInRiverOrEnemyHalf'] ?? null,
            earliestBaron: $data['earliestBaron'] ?? null,
            earliestDragonTakedown: $data['earliestDragonTakedown'] ?? null,
            earliestElderDragon: $data['earliestElderDragon'] ?? null,
            earlyLaningPhaseGoldExpAdvantage: $data['earlyLaningPhaseGoldExpAdvantage'] ?? null,
            fasterSupportQuestCompletion: $data['fasterSupportQuestCompletion'] ?? null,
            fastestLegendary: $data['fastestLegendary'] ?? null,
            hadAfkTeammate: $data['hadAfkTeammate'] ?? null,
            highestChampionDamage: $data['highestChampionDamage'] ?? null,
            highestCrowdControlScore: $data['highestCrowdControlScore'] ?? null,
            highestWardKills: $data['highestWardKills'] ?? null,
            junglerKillsEarlyJungle: $data['junglerKillsEarlyJungle'] ?? null,
            killsOnLanersEarlyJungleAsJungler: $data['killsOnLanersEarlyJungleAsJungler'] ?? null,
            laningPhaseGoldExpAdvantage: $data['laningPhaseGoldExpAdvantage'] ?? null,
            legendaryCount: $data['legendaryCount'] ?? null,
            maxCsAdvantageOnLaneOpponent: $data['maxCsAdvantageOnLaneOpponent'] ?? null,
            maxLevelLeadLaneOpponent: $data['maxLevelLeadLaneOpponent'] ?? null,
            mostWardsDestroyedOneSweeper: $data['mostWardsDestroyedOneSweeper'] ?? null,
            mythicItemUsed: $data['mythicItemUsed'] ?? null,
            playedChampSelectPosition: $data['playedChampSelectPosition'] ?? null,
            soloTurretsLategame: $data['soloTurretsLategame'] ?? null,
            takedownsFirst25Minutes: $data['takedownsFirst25Minutes'] ?? null,
            teleportTakedowns: $data['teleportTakedowns'] ?? null,
            thirdInhibitorDestroyedTime: $data['thirdInhibitorDestroyedTime'] ?? null,
            threeWardsOneSweeperCount: $data['threeWardsOneSweeperCount'] ?? null,
            visionScoreAdvantageLaneOpponent: $data['visionScoreAdvantageLaneOpponent'] ?? null,
            InfernalScalePickup: $data['InfernalScalePickup'] ?? null,
            fistBumpParticipation: $data['fistBumpParticipation'] ?? null,
            voidMonsterKill: $data['voidMonsterKill'] ?? null,
            abilityUses: $data['abilityUses'] ?? null,
            acesBefore15Minutes: $data['acesBefore15Minutes'] ?? null,
            alliedJungleMonsterKills: $data['alliedJungleMonsterKills'] ?? null,
            baronTakedowns: $data['baronTakedowns'] ?? null,
            blastConeOppositeOpponentCount: $data['blastConeOppositeOpponentCount'] ?? null,
            bountyGold: $data['bountyGold'] ?? null,
            buffsStolen: $data['buffsStolen'] ?? null,
            completeSupportQuestInTime: $data['completeSupportQuestInTime'] ?? null,
            controlWardsPlaced: $data['controlWardsPlaced'] ?? null,
            damagePerMinute: $data['damagePerMinute'] ?? null,
            damageTakenOnTeamPercentage: $data['damageTakenOnTeamPercentage'] ?? null,
            dancedWithRiftHerald: $data['dancedWithRiftHerald'] ?? null,
            deathsByEnemyChamps: $data['deathsByEnemyChamps'] ?? null,
            dodgeSkillShotsSmallWindow: $data['dodgeSkillShotsSmallWindow'] ?? null,
            doubleAces: $data['doubleAces'] ?? null,
            dragonTakedowns: $data['dragonTakedowns'] ?? null,
            legendaryItemUsed: $data['legendaryItemUsed'] ?? null,
            effectiveHealAndShielding: $data['effectiveHealAndShielding'] ?? null,
            elderDragonKillsWithOpposingSoul: $data['elderDragonKillsWithOpposingSoul'] ?? null,
            elderDragonMultikills: $data['elderDragonMultikills'] ?? null,
            enemyChampionImmobilizations: $data['enemyChampionImmobilizations'] ?? null,
            enemyJungleMonsterKills: $data['enemyJungleMonsterKills'] ?? null,
            epicMonsterKillsNearEnemyJungler: $data['epicMonsterKillsNearEnemyJungler'] ?? null,
            epicMonsterKillsWithin30SecondsOfSpawn: $data['epicMonsterKillsWithin30SecondsOfSpawn'] ?? null,
            epicMonsterSteals: $data['epicMonsterSteals'] ?? null,
            epicMonsterStolenWithoutSmite: $data['epicMonsterStolenWithoutSmite'] ?? null,
            firstTurretKilled: $data['firstTurretKilled'] ?? null,
            firstTurretKilledTime: $data['firstTurretKilledTime'] ?? null,
            flawlessAces: $data['flawlessAces'] ?? null,
            fullTeamTakedown: $data['fullTeamTakedown'] ?? null,
            gameLength: $data['gameLength'] ?? null,
            getTakedownsInAllLanesEarlyJungleAsLaner: $data['getTakedownsInAllLanesEarlyJungleAsLaner'] ?? null,
            goldPerMinute: $data['goldPerMinute'] ?? null,
            hadOpenNexus: $data['hadOpenNexus'] ?? null,
            immobilizeAndKillWithAlly: $data['immobilizeAndKillWithAlly'] ?? null,
            initialBuffCount: $data['initialBuffCount'] ?? null,
            initialCrabCount: $data['initialCrabCount'] ?? null,
            jungleCsBefore10Minutes: $data['jungleCsBefore10Minutes'] ?? null,
            junglerTakedownsNearDamagedEpicMonster: $data['junglerTakedownsNearDamagedEpicMonster'] ?? null,
            kda: $data['kda'] ?? null,
            killAfterHiddenWithAlly: $data['killAfterHiddenWithAlly'] ?? null,
            killedChampTookFullTeamDamageSurvived: $data['killedChampTookFullTeamDamageSurvived'] ?? null,
            killingSprees: $data['killingSprees'] ?? null,
            killParticipation: $data['killParticipation'] ?? null,
            killsNearEnemyTurret: $data['killsNearEnemyTurret'] ?? null,
            killsOnOtherLanesEarlyJungleAsLaner: $data['killsOnOtherLanesEarlyJungleAsLaner'] ?? null,
            killsOnRecentlyHealedByAramPack: $data['killsOnRecentlyHealedByAramPack'] ?? null,
            killsUnderOwnTurret: $data['killsUnderOwnTurret'] ?? null,
            killsWithHelpFromEpicMonster: $data['killsWithHelpFromEpicMonster'] ?? null,
            knockEnemyIntoTeamAndKill: $data['knockEnemyIntoTeamAndKill'] ?? null,
            kTurretsDestroyedBeforePlatesFall: $data['kTurretsDestroyedBeforePlatesFall'] ?? null,
            landSkillShotsEarlyGame: $data['landSkillShotsEarlyGame'] ?? null,
            laneMinionsFirst10Minutes: $data['laneMinionsFirst10Minutes'] ?? null,
            lostAnInhibitor: $data['lostAnInhibitor'] ?? null,
            maxKillDeficit: $data['maxKillDeficit'] ?? null,
            mejaisFullStackInTime: $data['mejaisFullStackInTime'] ?? null,
            moreEnemyJungleThanOpponent: $data['moreEnemyJungleThanOpponent'] ?? null,
            multiKillOneSpell: $data['multiKillOneSpell'] ?? null,
            multikills: $data['multikills'] ?? null,
            multikillsAfterAggressiveFlash: $data['multikillsAfterAggressiveFlash'] ?? null,
            multiTurretRiftHeraldCount: $data['multiTurretRiftHeraldCount'] ?? null,
            outerTurretExecutesBefore10Minutes: $data['outerTurretExecutesBefore10Minutes'] ?? null,
            outnumberedKills: $data['outnumberedKills'] ?? null,
            outnumberedNexusKill: $data['outnumberedNexusKill'] ?? null,
            perfectDragonSoulsTaken: $data['perfectDragonSoulsTaken'] ?? null,
            perfectGame: $data['perfectGame'] ?? null,
            pickKillWithAlly: $data['pickKillWithAlly'] ?? null,
            poroExplosions: $data['poroExplosions'] ?? null,
            quickCleanse: $data['quickCleanse'] ?? null,
            quickFirstTurret: $data['quickFirstTurret'] ?? null,
            quickSoloKills: $data['quickSoloKills'] ?? null,
            riftHeraldTakedowns: $data['riftHeraldTakedowns'] ?? null,
            saveAllyFromDeath: $data['saveAllyFromDeath'] ?? null,
            scuttleCrabKills: $data['scuttleCrabKills'] ?? null,
            shortestTimeToAceFromFirstTakedown: $data['shortestTimeToAceFromFirstTakedown'] ?? null,
            skillshotsDodged: $data['skillshotsDodged'] ?? null,
            skillshotsHit: $data['skillshotsHit'] ?? null,
            snowballsHit: $data['snowballsHit'] ?? null,
            soloBaronKills: $data['soloBaronKills'] ?? null,
            SWARM_DefeatAatrox: $data['SWARM_DefeatAatrox'] ?? null,
            SWARM_DefeatBriar: $data['SWARM_DefeatBriar'] ?? null,
            SWARM_DefeatMiniBosses: $data['SWARM_DefeatMiniBosses'] ?? null,
            SWARM_EvolveWeapon: $data['SWARM_EvolveWeapon'] ?? null,
            SWARM_Have3Passives: $data['SWARM_Have3Passives'] ?? null,
            SWARM_KillEnemy: $data['SWARM_KillEnemy'] ?? null,
            SWARM_PickupGold: $data['SWARM_PickupGold'] ?? null,
            SWARM_ReachLevel50: $data['SWARM_ReachLevel50'] ?? null,
            SWARM_Survive15Min: $data['SWARM_Survive15Min'] ?? null,
            SWARM_WinWith5EvolvedWeapons: $data['SWARM_WinWith5EvolvedWeapons'] ?? null,
            soloKills: $data['soloKills'] ?? null,
            stealthWardsPlaced: $data['stealthWardsPlaced'] ?? null,
            survivedSingleDigitHpCount: $data['survivedSingleDigitHpCount'] ?? null,
            survivedThreeImmobilizesInFight: $data['survivedThreeImmobilizesInFight'] ?? null,
            takedownOnFirstTurret: $data['takedownOnFirstTurret'] ?? null,
            takedowns: $data['takedowns'] ?? null,
            takedownsAfterGainingLevelAdvantage: $data['takedownsAfterGainingLevelAdvantage'] ?? null,
            takedownsBeforeJungleMinionSpawn: $data['takedownsBeforeJungleMinionSpawn'] ?? null,
            takedownsFirstXMinutes: $data['takedownsFirstXMinutes'] ?? null,
            takedownsInAlcove: $data['takedownsInAlcove'] ?? null,
            takedownsInEnemyFountain: $data['takedownsInEnemyFountain'] ?? null,
            teamBaronKills: $data['teamBaronKills'] ?? null,
            teamDamagePercentage: $data['teamDamagePercentage'] ?? null,
            teamElderDragonKills: $data['teamElderDragonKills'] ?? null,
            teamRiftHeraldKills: $data['teamRiftHeraldKills'] ?? null,
            tookLargeDamageSurvived: $data['tookLargeDamageSurvived'] ?? null,
            turretPlatesTaken: $data['turretPlatesTaken'] ?? null,
            turretsTakenWithRiftHerald: $data['turretsTakenWithRiftHerald'] ?? null,
            turretTakedowns: $data['turretTakedowns'] ?? null,
            twentyMinionsIn3SecondsCount: $data['twentyMinionsIn3SecondsCount'] ?? null,
            twoWardsOneSweeperCount: $data['twoWardsOneSweeperCount'] ?? null,
            unseenRecalls: $data['unseenRecalls'] ?? null,
            visionScorePerMinute: $data['visionScorePerMinute'] ?? null,
            wardsGuarded: $data['wardsGuarded'] ?? null,
            wardTakedowns: $data['wardTakedowns'] ?? null,
            wardTakedownsBefore20M: $data['wardTakedownsBefore20M'] ?? null
        );
    }
}
