<?php

namespace App\Services\Riot\Match;

class ParticipantDto
{
    public function __construct(
        public int $allInPings,
        public int $assistMePings,
        public int $assists,
        public int $baronKills,
        public int $bountyLevel,
        public int $champExperience,
        public int $champLevel,
        public int $championId,
        public string $championName,
        public int $commandPings,
        public int $championTransform,
        public int $consumablesPurchased,
        public ?ChallengesDto $challenges,
        public int $damageDealtToBuildings,
        public int $damageDealtToObjectives,
        public int $damageDealtToTurrets,
        public int $damageSelfMitigated,
        public int $deaths,
        public int $detectorWardsPlaced,
        public int $doubleKills,
        public int $dragonKills,
        public bool $eligibleForProgression,
        public int $enemyMissingPings,
        public int $enemyVisionPings,
        public bool $firstBloodAssist,
        public bool $firstBloodKill,
        public bool $firstTowerAssist,
        public bool $firstTowerKill,
        public bool $gameEndedInEarlySurrender,
        public bool $gameEndedInSurrender,
        public int $holdPings,
        public int $getBackPings,
        public int $goldEarned,
        public int $goldSpent,
        public string $individualPosition,
        public int $inhibitorKills,
        public int $inhibitorTakedowns,
        public int $inhibitorsLost,
        public int $item0,
        public int $item1,
        public int $item2,
        public int $item3,
        public int $item4,
        public int $item5,
        public int $item6,
        public int $itemsPurchased,
        public int $killingSprees,
        public int $kills,
        public string $lane,
        public int $largestCriticalStrike,
        public int $largestKillingSpree,
        public int $largestMultiKill,
        public int $longestTimeSpentLiving,
        public int $magicDamageDealt,
        public int $magicDamageDealtToChampions,
        public int $magicDamageTaken,
        public ?MissionsDto $missions,
        public int $neutralMinionsKilled,
        public int $needVisionPings,
        public int $nexusKills,
        public int $nexusTakedowns,
        public int $nexusLost,
        public int $objectivesStolen,
        public int $objectivesStolenAssists,
        public int $onMyWayPings,
        public int $participantId,
        public int $playerScore0,
        public int $playerScore1,
        public int $playerScore2,
        public int $playerScore3,
        public int $playerScore4,
        public int $playerScore5,
        public int $playerScore6,
        public int $playerScore7,
        public int $playerScore8,
        public int $playerScore9,
        public int $playerScore10,
        public int $playerScore11,
        public int $pentaKills,
        public ?PerksDto $perks,
        public int $physicalDamageDealt,
        public int $physicalDamageDealtToChampions,
        public int $physicalDamageTaken,
        public int $placement,
        public int $playerAugment1,
        public int $playerAugment2,
        public int $playerAugment3,
        public int $playerAugment4,
        public int $playerSubteamId,
        public int $pushPings,
        public int $profileIcon,
        public string $puuid,
        public int $quadraKills,
        public string $riotIdGameName,
        public string $riotIdTagline,
        public string $role,
        public int $sightWardsBoughtInGame,
        public int $spell1Casts,
        public int $spell2Casts,
        public int $spell3Casts,
        public int $spell4Casts,
        public int $subteamPlacement,
        public int $summoner1Casts,
        public int $summoner1Id,
        public int $summoner2Casts,
        public int $summoner2Id,
        public string $summonerId,
        public int $summonerLevel,
        public string $summonerName,
        public bool $teamEarlySurrendered,
        public int $teamId,
        public string $teamPosition,
        public int $timeCCingOthers,
        public int $timePlayed,
        public int $totalAllyJungleMinionsKilled,
        public int $totalDamageDealt,
        public int $totalDamageDealtToChampions,
        public int $totalDamageShieldedOnTeammates,
        public int $totalDamageTaken,
        public int $totalEnemyJungleMinionsKilled,
        public int $totalHeal,
        public int $totalHealsOnTeammates,
        public int $totalMinionsKilled,
        public int $totalTimeCCDealt,
        public int $totalTimeSpentDead,
        public int $totalUnitsHealed,
        public int $tripleKills,
        public int $trueDamageDealt,
        public int $trueDamageDealtToChampions,
        public int $trueDamageTaken,
        public int $turretKills,
        public int $turretTakedowns,
        public int $turretsLost,
        public int $unrealKills,
        public int $visionScore,
        public int $visionClearedPings,
        public int $visionWardsBoughtInGame,
        public int $wardsKilled,
        public int $wardsPlaced,
        public bool $win
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            allInPings: $data['allInPings'] ?? 0,
            assistMePings: $data['assistMePings'] ?? 0,
            assists: $data['assists'] ?? 0,
            baronKills: $data['baronKills'] ?? 0,
            bountyLevel: $data['bountyLevel'] ?? 0,
            champExperience: $data['champExperience'] ?? 0,
            champLevel: $data['champLevel'] ?? 0,
            championId: $data['championId'] ?? 0,
            championName: $data['championName'] ?? '',
            commandPings: $data['commandPings'] ?? 0,
            championTransform: $data['championTransform'] ?? 0,
            consumablesPurchased: $data['consumablesPurchased'] ?? 0,
            challenges: isset($data['challenges']) ? ChallengesDto::fromArray($data['challenges']) : null,
            damageDealtToBuildings: $data['damageDealtToBuildings'] ?? 0,
            damageDealtToObjectives: $data['damageDealtToObjectives'] ?? 0,
            damageDealtToTurrets: $data['damageDealtToTurrets'] ?? 0,
            damageSelfMitigated: $data['damageSelfMitigated'] ?? 0,
            deaths: $data['deaths'] ?? 0,
            detectorWardsPlaced: $data['detectorWardsPlaced'] ?? 0,
            doubleKills: $data['doubleKills'] ?? 0,
            dragonKills: $data['dragonKills'] ?? 0,
            eligibleForProgression: $data['eligibleForProgression'] ?? false,
            enemyMissingPings: $data['enemyMissingPings'] ?? 0,
            enemyVisionPings: $data['enemyVisionPings'] ?? 0,
            firstBloodAssist: $data['firstBloodAssist'] ?? false,
            firstBloodKill: $data['firstBloodKill'] ?? false,
            firstTowerAssist: $data['firstTowerAssist'] ?? false,
            firstTowerKill: $data['firstTowerKill'] ?? false,
            gameEndedInEarlySurrender: $data['gameEndedInEarlySurrender'] ?? false,
            gameEndedInSurrender: $data['gameEndedInSurrender'] ?? false,
            holdPings: $data['holdPings'] ?? 0,
            getBackPings: $data['getBackPings'] ?? 0,
            goldEarned: $data['goldEarned'] ?? 0,
            goldSpent: $data['goldSpent'] ?? 0,
            individualPosition: $data['individualPosition'] ?? '',
            inhibitorKills: $data['inhibitorKills'] ?? 0,
            inhibitorTakedowns: $data['inhibitorTakedowns'] ?? 0,
            inhibitorsLost: $data['inhibitorsLost'] ?? 0,
            item0: $data['item0'] ?? 0,
            item1: $data['item1'] ?? 0,
            item2: $data['item2'] ?? 0,
            item3: $data['item3'] ?? 0,
            item4: $data['item4'] ?? 0,
            item5: $data['item5'] ?? 0,
            item6: $data['item6'] ?? 0,
            itemsPurchased: $data['itemsPurchased'] ?? 0,
            killingSprees: $data['killingSprees'] ?? 0,
            kills: $data['kills'] ?? 0,
            lane: $data['lane'] ?? '',
            largestCriticalStrike: $data['largestCriticalStrike'] ?? 0,
            largestKillingSpree: $data['largestKillingSpree'] ?? 0,
            largestMultiKill: $data['largestMultiKill'] ?? 0,
            longestTimeSpentLiving: $data['longestTimeSpentLiving'] ?? 0,
            magicDamageDealt: $data['magicDamageDealt'] ?? 0,
            magicDamageDealtToChampions: $data['magicDamageDealtToChampions'] ?? 0,
            magicDamageTaken: $data['magicDamageTaken'] ?? 0,
            missions: isset($data['missions']) ? MissionsDto::fromArray($data['missions']) : null,
            neutralMinionsKilled: $data['neutralMinionsKilled'] ?? 0,
            needVisionPings: $data['needVisionPings'] ?? 0,
            nexusKills: $data['nexusKills'] ?? 0,
            nexusTakedowns: $data['nexusTakedowns'] ?? 0,
            nexusLost: $data['nexusLost'] ?? 0,
            objectivesStolen: $data['objectivesStolen'] ?? 0,
            objectivesStolenAssists: $data['objectivesStolenAssists'] ?? 0,
            onMyWayPings: $data['onMyWayPings'] ?? 0,
            participantId: $data['participantId'] ?? 0,
            playerScore0: $data['playerScore0'] ?? 0,
            playerScore1: $data['playerScore1'] ?? 0,
            playerScore2: $data['playerScore2'] ?? 0,
            playerScore3: $data['playerScore3'] ?? 0,
            playerScore4: $data['playerScore4'] ?? 0,
            playerScore5: $data['playerScore5'] ?? 0,
            playerScore6: $data['playerScore6'] ?? 0,
            playerScore7: $data['playerScore7'] ?? 0,
            playerScore8: $data['playerScore8'] ?? 0,
            playerScore9: $data['playerScore9'] ?? 0,
            playerScore10: $data['playerScore10'] ?? 0,
            playerScore11: $data['playerScore11'] ?? 0,
            pentaKills: $data['pentaKills'] ?? 0,
            perks: isset($data['perks']) ? PerksDto::fromArray($data['perks']) : null,
            physicalDamageDealt: $data['physicalDamageDealt'] ?? 0,
            physicalDamageDealtToChampions: $data['physicalDamageDealtToChampions'] ?? 0,
            physicalDamageTaken: $data['physicalDamageTaken'] ?? 0,
            placement: $data['placement'] ?? 0,
            playerAugment1: $data['playerAugment1'] ?? 0,
            playerAugment2: $data['playerAugment2'] ?? 0,
            playerAugment3: $data['playerAugment3'] ?? 0,
            playerAugment4: $data['playerAugment4'] ?? 0,
            playerSubteamId: $data['playerSubteamId'] ?? 0,
            pushPings: $data['pushPings'] ?? 0,
            profileIcon: $data['profileIcon'] ?? 0,
            puuid: $data['puuid'] ?? '',
            quadraKills: $data['quadraKills'] ?? 0,
            riotIdGameName: $data['riotIdGameName'] ?? '',
            riotIdTagline: $data['riotIdTagline'] ?? '',
            role: $data['role'] ?? '',
            sightWardsBoughtInGame: $data['sightWardsBoughtInGame'] ?? 0,
            spell1Casts: $data['spell1Casts'] ?? 0,
            spell2Casts: $data['spell2Casts'] ?? 0,
            spell3Casts: $data['spell3Casts'] ?? 0,
            spell4Casts: $data['spell4Casts'] ?? 0,
            subteamPlacement: $data['subteamPlacement'] ?? 0,
            summoner1Casts: $data['summoner1Casts'] ?? 0,
            summoner1Id: $data['summoner1Id'] ?? 0,
            summoner2Casts: $data['summoner2Casts'] ?? 0,
            summoner2Id: $data['summoner2Id'] ?? 0,
            summonerId: $data['summonerId'] ?? '',
            summonerLevel: $data['summonerLevel'] ?? 0,
            summonerName: $data['summonerName'] ?? '',
            teamEarlySurrendered: $data['teamEarlySurrendered'] ?? false,
            teamId: $data['teamId'] ?? 0,
            teamPosition: $data['teamPosition'] ?? '',
            timeCCingOthers: $data['timeCCingOthers'] ?? 0,
            timePlayed: $data['timePlayed'] ?? 0,
            totalAllyJungleMinionsKilled: $data['totalAllyJungleMinionsKilled'] ?? 0,
            totalDamageDealt: $data['totalDamageDealt'] ?? 0,
            totalDamageDealtToChampions: $data['totalDamageDealtToChampions'] ?? 0,
            totalDamageShieldedOnTeammates: $data['totalDamageShieldedOnTeammates'] ?? 0,
            totalDamageTaken: $data['totalDamageTaken'] ?? 0,
            totalEnemyJungleMinionsKilled: $data['totalEnemyJungleMinionsKilled'] ?? 0,
            totalHeal: $data['totalHeal'] ?? 0,
            totalHealsOnTeammates: $data['totalHealsOnTeammates'] ?? 0,
            totalMinionsKilled: $data['totalMinionsKilled'] ?? 0,
            totalTimeCCDealt: $data['totalTimeCCDealt'] ?? 0,
            totalTimeSpentDead: $data['totalTimeSpentDead'] ?? 0,
            totalUnitsHealed: $data['totalUnitsHealed'] ?? 0,
            tripleKills: $data['tripleKills'] ?? 0,
            trueDamageDealt: $data['trueDamageDealt'] ?? 0,
            trueDamageDealtToChampions: $data['trueDamageDealtToChampions'] ?? 0,
            trueDamageTaken: $data['trueDamageTaken'] ?? 0,
            turretKills: $data['turretKills'] ?? 0,
            turretTakedowns: $data['turretTakedowns'] ?? 0,
            turretsLost: $data['turretsLost'] ?? 0,
            unrealKills: $data['unrealKills'] ?? 0,
            visionScore: $data['visionScore'] ?? 0,
            visionClearedPings: $data['visionClearedPings'] ?? 0,
            visionWardsBoughtInGame: $data['visionWardsBoughtInGame'] ?? 0,
            wardsKilled: $data['wardsKilled'] ?? 0,
            wardsPlaced: $data['wardsPlaced'] ?? 0,
            win: $data['win'] ?? false
        );
    }
}
